apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-loadbalancer
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 3000
