apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
  labels:
    app: kittens-app-label
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: kittens-app-label
  template:
    metadata:
      labels:
        app: kittens-app-label
    spec:
      # restartPolicy: Never
      containers:
        - name: kittens-app
          image: {{ .Values.app.image }}
          imagePullPolicy: "IfNotPresent"
          command: ['sh', 'scripts/serve.sh']
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: kittens-app-config
