apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  labels:
    app: kittens-app-label
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: kittens-app-label
