require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.4.9
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/
    - tmp/

Style/Documentation:
  Enabled: false

RSpec/FilePath:
  Enabled: false
