version: '2.0'

services:
  app:
    image: vbyno/kittens-store:1.0.0
    environment:
      DATABASE_URL: postgres://postgres_user:pass@db:5432/kittens_store
      RACK_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DB_PORT: 5432
    command: ['sh', 'scripts/serve.sh']
    ports:
      - '80:3000'
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data/db:/var/lib/postgresql/data
