name: cleanup
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'ops/infrastructure/live_ci'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy --auto-approve
      - name: Delete the remaining load balancers
        run: aws elb describe-load-balancers --region ${{ secrets.AWS_REGION }} | jq '.LoadBalancerDescriptions | .[] | .LoadBalancerName' | xargs -L1 aws elb delete-load-balancer --load-balancer-name
        continue-on-error: true
